FROM node:slim as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1-alpine3.18-slim as deploy
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
