apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value:  admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value:  admin
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "true"
        resources:
          # limits:
          #   memory: "1000Mi"
          #   cpu: "1000m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
